# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
- master

pool: demopipeline
strategy:
  matrix:
    Python310:
      python.version: '3.10'

steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'
  - script: pip install -r requirements.txt
    displayName: 'Install requirements'
  - script: python3 hello2.py
  - task: PublishTestResults@2
    condition: succeededOrFailed()
    inputs:
      testResultsFiles: '**/test-*.xml'
      testRunTitle: 'Publish test results for Python $(python.version)'
  - task: PythonScript@0
    inputs:
      scriptSource: inline
      script: |
        import sys
        print ('Executing script file is:', str(sys.argv[0]))
        print ('The arguments are:', str(sys.argv))
        import argparse
        parser = argparse.ArgumentParser()
        parser.add_argument("--world", help="Provide the name of the world to greet.")
        args = parser.parse_args()
        print ('Hello ', args.world)
      arguments: --world Venus